:Author: Altuğ Bakan
:Date: 19/02/2022
:Revision: version 1
:License: MIT

= Arduino Spotify Controller

This project has won the 3rd place 🥉 award on https://blog.arduino.cc/2022/03/26/top-three-arduino-cloud-games-projects-revealed/[Arduino Cloud Games 2022]!

Makes you control your Spotify player using your Arduino Oplà IoT kit. Created for #cloudgames2022.

Please check the https://create.arduino.cc/projecthub/Altug/opla-spotify-controller-6e7bc4[Arduino Project Hub] page for more information.

== Step 1: Installation
1. Enter your WiFi SSID and password to Secret tab
2. Create an Application on https://developer.spotify.com/dashboard/applications
3. Enter your Client ID and Client Secret to Secret tab
4. Enter http://[ARDUINO_IP_ADDRESS]/redirect/ to your Spotify app, for example http://192.168.1.105/redirect/. You can find your IP address after booting up the Arduino

== Step 2: Assemble the circuit

Assemble the circuit following the diagram assembly.png attached to the sketch.

== Step 3: Load the code

Upload the code contained in this sketch on to your board.

=== Folder structure

....
 sketch                       => Arduino sketch folder
  ├── Spotify_Controller.ino  => main Arduino file
  ├── thingProperties.h       => Arduino IoT Cloud properties
  ├── spotifyLogo.h           => Spotify logo image
  ├── assembly.png            => an image of the assembly
  └── ReadMe.adoc             => this file
....

=== License
This project is released under an {License} License.

=== Contributing
To contribute to this project please open a pull request on GitHub.

=== BOM
|===
| ID | Part name              | Part number | Quantity
| OP | Arduino Oplà IoT Kit   | AKX00026    | 1
| SP | Spotify Premium        | -           | 1
|===
