// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


String artist_name;
String ip_address;
String song_name;
int song_length;
int volume_percent;
bool is_active;
bool is_playing;

void initProperties(){

  ArduinoCloud.addProperty(artist_name, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ip_address, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(song_name, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(song_length, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(volume_percent, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(is_active, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(is_playing, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
